(function() {var implementors = {};
implementors["protobuf"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptor/enum.FieldDescriptorProto_Type.html' title='protobuf::descriptor::FieldDescriptorProto_Type'>FieldDescriptorProto_Type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptor/enum.FieldDescriptorProto_Label.html' title='protobuf::descriptor::FieldDescriptorProto_Label'>FieldDescriptorProto_Label</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptor/enum.FileOptions_OptimizeMode.html' title='protobuf::descriptor::FileOptions_OptimizeMode'>FileOptions_OptimizeMode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptor/enum.FieldOptions_CType.html' title='protobuf::descriptor::FieldOptions_CType'>FieldOptions_CType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptor/enum.FieldOptions_JSType.html' title='protobuf::descriptor::FieldOptions_JSType'>FieldOptions_JSType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='protobuf/reflect/struct.EnumValueDescriptor.html' title='protobuf::reflect::EnumValueDescriptor'>EnumValueDescriptor</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/stream/wire_format/enum.WireType.html' title='protobuf::stream::wire_format::WireType'>WireType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='protobuf/stream/wire_format/struct.Tag.html' title='protobuf::stream::wire_format::Tag'>Tag</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='protobuf/descriptorx/enum.Syntax.html' title='protobuf::descriptorx::Syntax'>Syntax</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
